### ISSUE TITLE
Review Button Addons

### ISSUE THREAD

**Issue by vincentmorneau** [vincentmorneau/apex-bootstrap4#27]
Need to understand why such px units in _apex_buttons.scss:

``` scss
.btn-left-addon {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}

.btn-right-addon {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    margin-left: -22px;
}

.input-btn-left-addon {
    margin-left: -14px;
    margin-top: 0.1px;
    input {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }
}

.input-btn-right-addon {
    margin-right: -9px;
    margin-top: 0.1px;
    input {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }
}

.input-btn-addon {
    margin-right: -9px;
    margin-left: -14px;
    margin-top: 0.1px;

    input {
        border-radius: 0;
    }
}
```
